linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  timeout: 5m
