name: lint

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: lookup golang version
        run: echo "GO_VERSION=$(make go-version)" >> $GITHUB_ENV
      - name: install golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: lookup linter version
        run: echo "LINTER_VERSION=$(make linter-version)" >> $GITHUB_ENV
      - name: run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v${{ env.LINTER_VERSION }}
