name:

on:
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lookup linter version
        run: make linter_version >> $LINTER_VERSION
      - name: run linter
        uses: golangci/golangci-lint-action@v2
          with:
            version: "v${{ env.LINTER_VERSION }}"
